apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cleaner
  namespace: kyma-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cleaner
  template:
    metadata:
      labels:
        app: test-cleaner
    spec:
      serviceAccountName: cleaner-sa
      initContainers:
        - name: init-cleanup
          image: europe-docker.pkg.dev/kyma-project/prod/cp-mod-cleaner:latest
          imagePullPolicy: Always
      containers:
        - name: test-cleaner
          image: busybox
          command: ['sh', '-c', 'echo The app is running! && sleep 3600']
