apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleaner-admin-sa
  namespace: kyma-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleaner-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: cleaner-admin-sa
    namespace: kyma-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io